aioftp/server.py, tests/test-connection.py
If not - we get tons of listening (and not actually needed/used) connections
=> close data connection after client disconnects

.gitignore, aioftp/client.py, setup.py
According to RFC 959 (https://www.ietf.org/rfc/rfc959.txt), the end-of-line sequence for FTP commands should be CRLF and not LF. Most FTP server implementations don't care and support either, but Microsoft's IIS/FTP solution is picky and will return a 451 error response due to the invalid line termination (see https://support.microsoft.com/en-us/kb/2505047).
=> Updated end of line character sequence to CRLF rather than LF

aioftp/client.py
If there is an exception before the stream is opened(such as socket.gaierror) it will cause another exception when trying to close the stream(in async with).
=> Do not close stream if not opened

.travis.yml, README.rst
Let's switch from coveralls to codecov for sake of unification with other aio-libs projects.
Also codecov has a fancy **officially supported** [browser extension](https://docs.codecov.io/v4.3.6/docs/browser-extension).
=> Coveralls -> codecov

aioftp/server.py
If client disconnects during file upload, server exception is not consumed:
https://docs.python.org/3/library/asyncio-dev.html#detect-exceptions-never-consumed
=> Handle client side disconnection correctly

aioftp/server.py
Discard additional values from unpacking an ipv6 tuple.
Closes #63.
=> Resolve ipv6 error

aioftp/pathio.py, aioftp/server.py
Instead of a `Connection` object being passed a pointer to the main `PathIO` object it is passed the `PathIO` factory class which allows it to create it's own `PathIO` instance.
This allows the `Connection` to pass itself to the `PathIO` instance and allows all `PathIO` methods to access the `connection` object. 
This is useful if the IO operations need to know the username or password in order to function. For example for calling a third-party API and passing the credentials along.
Closes #66.
=> Move PathIO creation to connection

.travis.yml, aioftp/client.py, aioftp/common.py, aioftp/pathio.py, setup.py, tests/test-abort.py, tests/test-connection.py, tests/test-directory-actions.py
This adds support for Python 3.7 for async generators. That is, 
```py
async def __aiter__(self):
``` 
is not supported in Python 3.7. However, 
```py
def __aiter__(self):
```
is supported in all supported versions of this library.
This also bumps the travis build version.
In instances such as [this](https://github.com/Modelmat/aioftp/blob/3_7_update/aioftp/pathio.py#L452-L476) and [this](https://github.com/Modelmat/aioftp/blob/3_7_update/aioftp/client.py#L601-L679) a workaround has been used to support await statements that were previously in `__aiter__` however this decreases performance.
=> fix `__aiter__` must be plain function

aioftp/client.py, aioftp/server.py, setup.py, tests/common.py, tests/test-connection.py, tests/test-maximum-connections.py, tests/test-throttle.py
SSL support added.
https://github.com/aio-libs/aioftp/issues/37
=> Add implicit FTPS support

aioftp/server.py
This fixes the warning:
> ... server.py:878: PendingDeprecationWarning: Task.current_task() is
> deprecated, use asyncio.current_task() instead
as documented at https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.current_task:
> This method is deprecated and will be removed in Python 3.9. Use the
> asyncio.current_task() function instead.
The function `asyncio.current_task()` was only added in Python 3.7, and we're supporting earlier, hence the check on Python version.
=> Fix deprecation warning in Python 3.7

aioftp/server.py, history.rst
This is a small change to make `commands_mapping` perform all translation, removing the additional code that renamed `pass` to `pass_`.
Code utilizing `self.commands_mapping['pass_']` explicitly will break.
=> Rename 'pass_' to 'pass' in `commands_mapping` and remove special case

aioftp/client.py, aioftp/common.py, aioftp/errors.py, history.rst, tests/test_simple_functions.py
- Fix leap year bug at `parse_ls_date` method
- Make `parse_ls_date` method static
- Add base exception class
Nope.
Fixes #107 #109.
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`
=> Fix leap year (fixes #107 #109)

aioftp/client.py, aioftp/server.py, history.rst
Currently the user's password is printed in plaintext in the logs. This PR replaces the user's password in log files with stars.
The way this is done was borrowed from https://github.com/python/cpython/blob/master/Lib/ftplib.py#L186
Yes, they will no longer be able to see the password with which they are connecting in the log files
#111 
* Make sure to use full …
=> client/server: censor the user's password when logging (fixes #111)

aioftp/client.py, history.rst, tests/test_connection.py, tests/test_file.py, tests/test_passive.py
When using this library in the wild, I came across an ftp server that times out when attempting to start an epsv connection. Because it doesn't return an error code, the client never attempts to switch to regular pasv.
This change lets you pass default passive commands at creation of the client, and if no custom commands are used when creating the passive connection, these will be used. This means it is now possible for you to set client-wide passive commands which will be used whenever a method calls `get_passive_connection`.
If for some weird reason you were calling `get_passive_connection` with an empty list of commands, it will no longer result in a `ValueError`, because the default client passive commands will be used. But I have no idea why anyone would *ever* do that.
* name it …
=> client: add default client-wide passive commands

history.rst, tests/test_pathio.py
Fix `test_unlink_on_dir on POSIX-compatible` systems.
POSIX prescribes ([1]) `unlink(2)` to return EPERM when called on directories:
```
[EPERM]
The file named by path is a directory, and either the calling process does not have appropriate privileges, or the implementation prohibits using unlink() on directories.
```
and returning `EISDIR` in this case is Linux-specific behavior which does not happen on e.g. FreeBSD. So expect either of IsADirectoryError, PermissionError in the corresponding test.
[1] https://pubs.opengroup.org/onlinepubs/007904975/toc.htm
#117
* `.bugfix`: …
=> pathio: update expected exceptions list from unlink on directory (fixes #117)

docs/client_tutorial.rst
The tutorial didn't work for me because `Client.context()` assumed the second argument was the port, not the username. Using keyword arguments solves the problem.
Make the tutorial work with `aioftp == 0.18.0`
Only that the tutorial should work out the box!
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii …
=> docs: add keywords to Client.context

README.rst, aioftp/common.py, aioftp/server.py, docs/index.rst
Fix `DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.`
https://docs.python.org/3/library/asyncio-task.html?highlight=wait#asyncio-example-wait-coroutine
Nope.
No.
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with …
=> fix deprecation warning "explicit passing of coroutine objects to asyncio.wait()"

aioftp/server.py
Fix MLSD error on listing corrupt symbol link file
Some corrupt symbol link file point to non-exists file will cause MLSD error.
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`
=> server/mlsx: add path existance check to prevent symlink `stat` call failure

aioftp/server.py, tests/test_simple_functions.py
Sanitize paths so directory traversal is not possible anymore.
Only for users trying to exploit directory traversal. It will send these back to the home directory.
https://github.com/aio-libs/aioftp/issues/147
=> server: fix real directory resolve for windows (fixes #147)

.github/workflows/ci.yml, aioftp/server.py, tests/test_connection.py
This allows old FTP client to connect to AIOFtp server located behind
NAT.
The change adds support for clients using passive connections (PASV command) to a server located behind NAT
Passive connections can be opened with PASV command to server behind (IPv4) NAT
N/A
- [x ] I think the code is well written
- [x ] Unit tests for the changes exist
- [x ] Documentation reflects the changes
* `.misc`: A ticket has been closed, but it is not …
=> server: support PASV response with custom address

src/aioftp/__init__.py, src/aioftp/__main__.py, tests/test_connection.py
=> tests: fix ipv4 override test

src/aioftp/client.py, tests/test_file.py, tests/test_simple_functions.py
Make `test_simple_functions` tests pass on 3.14
Remove all DeprecationWarnings from pytest runs
Nothing changed for user
Fixes #189
=> adjust codebase for python 3.14
